version: '2'

services:
    rethinkdb:
        image: rethinkdb
        ports:
            - 8080:8080
            - 28015:28015
            - 29015:29015
    golang:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - rethinkdb
        links:
            - rethinkdb
        working_dir: /go/src/github.com/joaodias/hugito-backend
        volumes:
            - .:/go/src/github.com/joaodias/hugito-backend
        ports:
            - 4000:4000
        environment:
            - PORT=:4000
            - DBHOST=rethinkdb:28015
            - DBNAME=development
            - CLIENTID=f3387b979183f21efc69
            - SECRET=ff4f508cafe7537c811639f9e9f7d20221c6395d
        command: bash -c 'godep restore -v && cd rethinkdb && go run init.go && cd .. && fresh'
